AWSTemplateFormatVersion: "2010-09-09"
Description: "CFT Template for creation of AWS Config Rule"
Parameters:
  resourceTags:
    Type: "String"
    Default: ""
    Description: "Tags of Amazon EBS volumes for the rule to check, in JSON format."
  resourceId:
    Type: "String"
    Default: ""
    Description: "ID of Amazon EBS volume for the rule to check."
  recoveryPointAgeValue:
    Type: "String"
    Default: "1"
    Description: "Numerical value for maximum allowed age. No more than 744 for hours, 31 for days."
  recoveryPointAgeUnit:
    Type: "String"
    Default: "days"
    Description: "Unit of time for maximum allowed age. Accepted values: \u0027hours\u0027, \u0027days\u0027."
Resources: 
  ConfigRuleForEBSInBackupPlan: 
    Type: AWS::Config::ConfigRule
    Properties: 
      ConfigRuleName: "ConfigRuleForEBSInBackupPlan"
      Description: "Check if Amazon Elastic Block Store (Amazon EBS) volumes are added in backup plans of AWS Backup. The rule is NON_COMPLIANT if Amazon EBS volumes are not included in backup plans."
      Source:
        Owner: "AWS"
        SourceIdentifier: "EBS_IN_BACKUP_PLAN"
  ConfigRuleForEBSOptimizedInstance: 
    Type: AWS::Config::ConfigRule
    Properties: 
      ConfigRuleName: "ConfigRuleForEBSOptimizedInstance"
      Description: "Checks whether EBS optimization is enabled for your EC2 instances that can be EBS-optimized."
      Scope:
        ComplianceResourceTypes: [
          "AWS::EC2::Instance"
        ]
      Source:
        Owner: "AWS"
        SourceIdentifier: "EBS_OPTIMIZED_INSTANCE"
  ConfigRuleForEBSSnapshotPublicRestorableCheck: 
    Type: AWS::Config::ConfigRule
    Properties: 
      ConfigRuleName: "ConfigRuleForEBSSnapshotPublicRestorableCheck"
      Description: "Checks whether Amazon Elastic Block Store (Amazon EBS) snapshots are not publicly restorable. The rule is NON_COMPLIANT if one or more snapshots with RestorableByUserIds field are set to all, that is, Amazon EBS snapshots are public."
      Source:
        Owner: "AWS"
        SourceIdentifier: "EBS_SNAPSHOT_PUBLIC_RESTORABLE_CHECK"
  ConfigRuleForEC2EBSEncryptionByDefault: 
    Type: AWS::Config::ConfigRule
    Properties: 
      ConfigRuleName: "ConfigRuleForEC2EBSEncryptionByDefault"
      Description: "Check that Amazon Elastic Block Store (EBS) encryption is enabled by default. The rule is NON_COMPLIANT if the encryption is not enabled."
      Source:
        Owner: "AWS"
        SourceIdentifier: "EC2_EBS_ENCRYPTION_BY_DEFAULT"
  ConfigRuleForEBSLastBackupRecoveryPointCreated: 
    Type: AWS::Config::ConfigRule
    Properties: 
      ConfigRuleName: "ConfigRuleForEBSLastBackupRecoveryPointCreated"
      Conditions:
        resourceTags:
          !Not [!Equals [!Ref resourceTags, ""]]
        resourceId:
          !Not [!Equals [!Ref resourceId, ""]]
        recoveryPointAgeValue:
          !Not [!Equals [!Ref recoveryPointAgeValue, ""]]
        recoveryPointAgeUnit:
          !Not [!Equals [!Ref recoveryPointAgeUnit, ""]]

      Description: "Checks if a recovery point was created for Amazon Elastic Block Store (Amazon EBS). The rule is NON_COMPLIANT if the Amazon EBS volume does not have a corresponding recovery point created within the specified time period."
      InputParameters: |
        {
          "resourceTags": {
            "Fn::If": [
              "resourceTags",
              {
                "Ref": "resourceTags"
              },
              {
                "Ref": "AWS::NoValue"
              }
            ]
          },
          "resourceId": {
            "Fn::If": [
              "resourceId",
              {
                "Ref": "resourceId"
              },
              {
                "Ref": "AWS::NoValue"
              }
            ]
          },
          "recoveryPointAgeValue": {
            "Fn::If": [
              "recoveryPointAgeValue",
              {
                "Ref": "recoveryPointAgeValue"
              },
              {
                "Ref": "AWS::NoValue"
              }
            ]
          },
          "recoveryPointAgeUnit": {
            "Fn::If": [
              "recoveryPointAgeUnit",
              {
                "Ref": "recoveryPointAgeUnit"
              },
              {
                "Ref": "AWS::NoValue"
              }
            ]
          }
        }
      Scope:
        ComplianceResourceTypes: [
          "AWS::EC2::Volume"
        ]
      Source:
        Owner: "AWS"
        SourceIdentifier: "EBS_LAST_BACKUP_RECOVERY_POINT_CREATED"
      